# Generated by Django 2.0b1 on 2017-11-21 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
