# Generated by Django 2.0b1 on 2017-11-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_auto_20171124_1211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='attempt',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='response',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quizattempt',
            name='student',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.DeleteModel(
            name='QuestionAttempt',
        ),
        migrations.DeleteModel(
            name='QuizAttempt',
        ),
    ]
